#!/usr/bin/env bash

set -ex

BUILD_PATH="/tmp/cyanurus-$$"
INSTALL_PATH="/tmp/cyanurus"

BINUTILS_URL="http://ftp.gnu.org/gnu/binutils/binutils-2.24.tar.bz2"
GCC_URL="http://ftp.gnu.org/gnu/gcc/gcc-4.9.1/gcc-4.9.1.tar.bz2"
GDB_URL="http://ftp.gnu.org/gnu/gdb/gdb-7.8.tar.xz"
UTIL_LINUX_URL="http://ftp.kernel.org/pub/linux/utils/util-linux/v2.25/util-linux-2.25.1.tar.xz"

JOBS="$(grep processor /proc/cpuinfo | wc -l)"
BUILD_OPTION="--prefix=${INSTALL_PATH}"

if [ -d "${INSTALL_PATH}" ]; then
  echo "The directory already exists: ${INSTALL_PATH}" >&2
  exit 1
fi

mkdir ${INSTALL_PATH}

mkdir ${BUILD_PATH}
pushd ${BUILD_PATH}

wget ${BINUTILS_URL} -O binutils.tar.bz2
wget ${GCC_URL} -O gcc.tar.bz2
wget ${GDB_URL} -O gdb.tar.xz
wget ${UTIL_LINUX_URL} -O util-linux.tar.xz

tar jxfv binutils.tar.bz2
mv binutils-* binutils

tar jxfv gcc.tar.bz2
mv gcc-* gcc

tar Jxfv gdb.tar.xz
mv gdb-* gdb

tar Jxfv util-linux.tar.xz
mv util-linux-* util-linux

mkdir arm-none-eabi-binutils
pushd arm-none-eabi-binutils
../binutils/configure ${BUILD_OPTION} --target=arm-none-eabi --disable-nls --disable-werror
make -j${JOBS}
make install
popd

mkdir arm-none-eabi-gcc
pushd arm-none-eabi-gcc
../gcc/configure ${BUILD_OPTION} --target=arm-none-eabi --disable-nls --disable-threads --disable-shared --disable-libssp --enable-languages=c
make -j${JOBS}
make install
popd

mkdir arm-none-eabi-gdb
pushd arm-none-eabi-gdb
../gdb/configure ${BUILD_OPTION} --target=arm-none-eabi
make -j${JOBS}
make install
popd

pushd util-linux
./configure ${BUILD_OPTION} --disable-all-programs --enable-minix --disable-bash-completion
make -j${JOBS}
make install
popd

popd
rm -rf ${BUILD_PATH}
