#!/usr/bin/env bash

set -ex

BUILD_PATH="/tmp/cyanurus-$$"
INSTALL_PATH="/opt/cyanurus"
CACHE_PATH="/tmp/cyanurus-cache"

JOBS="$(grep processor /proc/cpuinfo | wc -l)"
BUILD_OPTION="--prefix=${INSTALL_PATH}"

GCC_VERSION="4.9.1"
QEMU_VERSION="${QEMU_VERSION:-v2.1.2}"
MUSL_VERSION="${MUSL_VERSION:-v1.1.4}"

CYANURUS_URL="git://git.local/cyanurus.git"
QEMU_URL="git://git.qemu.org/qemu.git"
MUSL_URL="git://git.musl-libc.org/musl"

BINUTILS_URL="http://ftp.gnu.org/gnu/binutils/binutils-2.24.tar.bz2"
GCC_URL="http://ftp.gnu.org/gnu/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.bz2"
GDB_URL="http://ftp.gnu.org/gnu/gdb/gdb-7.8.tar.xz"
UTIL_LINUX_URL="http://ftp.kernel.org/pub/linux/utils/util-linux/v2.25/util-linux-2.25.1.tar.xz"
RUBY_URL="http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.3.tar.gz"

export PATH=${INSTALL_PATH}/bin:${INSTALL_PATH}/sbin:$PATH

if [ ! -d "${INSTALL_PATH}" ]; then
  echo "The directory doesn't exists: ${INSTALL_PATH}" >&2
  exit 1
fi

fetch-tarball() {
  local url=$1
  local name=$2
  local cache="${CACHE_PATH}/$(basename ${url})"

  if [ ! -f ${cache} ]; then
    wget ${url} --no-verbose -O ${cache}
  fi

  tar xf ${cache}
  mv ${name}-* ${name}
}

fetch-git-repository() {
  local url=$1
  local name=$2
  local version=$3
  local cache="${CACHE_PATH}/${name}"

  if [ -d ${cache} ]; then
    pushd ${cache}
    git fetch origin
    git reset --hard origin/master
    git clean -x -f -f -d
    git submodule update --init
    popd
  else
    git clone --recursive ${url} ${cache}
  fi

  cp -r ${cache} ${name}
  pushd ${name}
  git checkout ${version} -b build
  git clean -x -f -f -d
  git submodule update --init
  popd
}

install-binutils() {
  local arch=$1

  mkdir ${arch}-binutils
  pushd ${arch}-binutils
  ../binutils/configure ${BUILD_OPTION} --target=${arch} --disable-nls --disable-werror
  make -j${JOBS}
  make install
  popd
}

install-gcc() {
  local arch=$1

  mkdir ${arch}-gcc
  pushd ${arch}-gcc
  ../gcc/configure ${BUILD_OPTION} --target=${arch} --disable-nls --disable-threads --disable-shared --disable-libssp --enable-languages=c
  make -j${JOBS}
  make install
  popd
}

install-gdb() {
  local arch=$1

  mkdir ${arch}-gdb
  pushd ${arch}-gdb
  ../gdb/configure ${BUILD_OPTION} --target=${arch}
  make -j${JOBS}
  make install
  popd
}

install-crt() {
  local arch=$1

  pushd cyanurus
  make -j${JOBS}
  make test
  install -m 0644 build/src/user/crt/crt0.o ${INSTALL_PATH}/lib/gcc/${arch}/${GCC_VERSION}/crt0.o
  popd
}

install-musl() {
  local arch=$1

  pushd musl
  CC="${arch}-gcc" CFLAGS="-Os -march=armv7-a -mfloat-abi=soft -marm" ./configure --disable-shared --prefix=${INSTALL_PATH}/${arch}
  make -j${JOBS}
  make install
  popd
}

install-util-linux() {
  pushd util-linux
  ./configure ${BUILD_OPTION} --disable-all-programs --enable-minix --disable-bash-completion
  make -j${JOBS}
  make install
  popd
}

install-qemu() {
  pushd qemu
  ./configure ${BUILD_OPTION} --target-list=arm-softmmu,arm-linux-user
  make -j${JOBS}
  make install
  popd
}

install-ruby() {
  pushd ruby
  ./configure ${BUILD_OPTION} --disable-install-doc
  make -j${JOBS}
  make install
  popd
}

test-toolchain() {
  pushd cyanurus
  make clean
  make -j${JOBS} CYANURUS_CC=arm-cyanurus-eabi-gcc
  make test
  popd
}

mkdir -p ${CACHE_PATH}
rm -rf ${INSTALL_PATH}/*

mkdir ${BUILD_PATH}
pushd ${BUILD_PATH}

fetch-tarball ${BINUTILS_URL}   binutils
fetch-tarball ${GCC_URL}        gcc
fetch-tarball ${GDB_URL}        gdb
fetch-tarball ${UTIL_LINUX_URL} util-linux
fetch-tarball ${RUBY_URL}       ruby

fetch-git-repository ${CYANURUS_URL} cyanurus master
fetch-git-repository ${QEMU_URL}     qemu     ${QEMU_VERSION}
fetch-git-repository ${MUSL_URL}     musl     ${MUSL_VERSION}

install-binutils arm-none-eabi
install-gcc      arm-none-eabi
install-gdb      arm-none-eabi

install-util-linux
install-qemu
install-ruby

install-binutils arm-cyanurus-eabi
install-gcc      arm-cyanurus-eabi
install-gdb      arm-cyanurus-eabi
install-crt      arm-cyanurus-eabi
install-musl     arm-cyanurus-eabi

test-toolchain

popd
rm -rf ${BUILD_PATH}

install -m 0755 bin/* ${INSTALL_PATH}/bin
